name: Hooks Starter CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # Jest26 在 NodeJS v10 会有问题
        node-version: [12.x, 14.x]
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
        env:
          CI: true
      - name: Unit Test
        run: npm run test
      - name: Codecov
        run: bash <(curl -s https://codecov.io/bash)
